// hooks
import React, { useState } from 'react';
import { useRouter } from 'next/router';
import useAuth from '../hooks/useAuth';

// components
import Head from 'next/head';

// utils
import isBrowser from '../utils/isBrowser';

function Home() {
  const router = useRouter();
  const { isAuth, Login } = useAuth();

  const [matricula, setMatricula] = useState('');
  const [senha, setSenha] = useState('');

  if (isBrowser && isAuth) {
    router.push('/analyze');
    return null;
  }

  const reset = () => {
    setSenha('');
    setMatricula('');
  };

  const onSubmit = async (e) => {
    e.preventDefault();
    await Login(matricula, senha);
    reset();
  };

  return (
    <>
      <Head>
        <title>Redação</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={onSubmit}>
        <input
          type="text"
          onChange={(e) => setMatricula(e.target.value)}
          value={matricula}
          minLength="2"
          maxLength="255"
          required
        />
        <input
          type="password"
          onChange={(e) => setSenha(e.target.value)}
          value={senha}
          minLength="2"
          maxLength="255"
          required
        />
        <button type="submit">Enviar</button>
      </form>
    </>
  );
}

export default Home;
